network: "SATRN"
charset: "./resources/krn_charset.txt"
resize_hw:
  height: 32
  width: 100
use_rgb: False
label_maxlen: 25
seed: 42
model_dir: "../saved_models/satrn_wo_pretrain"

hidden_size: 512
filter_size: 2048
enc_layers: 12
dec_layers: 6
num_heads: 8
dropout_rate: 0.9 
rot_stddev: 0.6

train:
  dataset_paths:
      - '../data/train_tfrecord/*.tfrecord' #"../data/train/MJS90/mjsynth_*_case-words-*.tfrecord"     # 9M   mjsynth train+valid+test
#       - "../data/train/MJS90/synth90_alpha_case-words-*.tfrecord" # 5.5M synthtext without special symbol
#       - "../data/train/MJS90/synth90_spe_case-words-*.tfrecord"   # 1.5M synthtext with special symbol
  dataset_portions:
    - 0.8 
    - 0.1
    - 0.1
  lowercase: False
  alphanumeric: False
  batch_size: 128
  num_threads: 8
  tune_from: ""
  max_num_steps: 250001
  verbose: False
  save_steps: 5000
  summary_steps: 1000
  optimizer:
    optimizer: 'Adam'
    learning_rate: 0.0003
    beta2: 0.999
    use_clr: True
    clr_step: 250000
    grad_clip_norm: 2.

valid:
  dataset_paths:
      - '../data/test_tfrecord/*.tfrecord'
  lowercase: False
  alphanumeric: False
  batch_size: 128
  steps: 1000

eval:
  dataset_paths: 
      - '../data/*.tfrecord'
  lowercase: False
  alphanumeric: False
  model_path: "../saved_models/satrn_wo_pretrain"
  batch_size: 128
  verbose: True

